

 in sklearn estimators refers to algorithms or models
classification - predicting this or that
regression - prediction of numerals ex(house price prediction)


In [3]:
from sklearn.datasets import fetch_california_housing
#house=fetch_calfornia_housing()
#house


# getting data ready

In [4]:
house=fetch_california_housing()

In [5]:
house

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [6]:
import pandas as pd
house_df=pd.DataFrame(house["data"],columns=['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'])

In [7]:
house_df


MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [8]:
house_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [9]:
house_df["target"]=house["target"]

Just added the target value to the DataaFrame  

In [10]:
house_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

Initiating and fitting the model 

In [11]:
house_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [12]:
house_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [13]:
import numpy as np
np.random.seed(43)

X=house_df.drop("target",axis=1)
y=house_df["target"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
X_train

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
72     1.7500      49.0  5.552632   1.342105       560.0  3.684211     37.81   
2602   2.1542      17.0  7.045045   1.554054       517.0  2.328829     41.01   
19784  2.3958      14.0  7.911111   1.455556       270.0  3.000000     40.76   
3405   6.8380      34.0  6.473592   1.008803      1598.0  2.813380     34.26   
12492  1.8512      38.0  3.578344   1.025478      1243.0  1.583439     38.57   
...       ...       ...       ...        ...         ...       ...       ...   
18448  5.3157      16.0  6.590551   1.106299       850.0  3.346457     37.23   
7985   2.5068      26.0  4.240693   1.067394      4066.0  2.609756     33.86   
18687  3.9340      18.0  5.268156   1.189944       544.0  3.039106     37.03   
19776  1.8375      21.0  5.372671   1.086957       982.0  3.049689     39.86   
14148  3.6125      36.0  4.969957   0.935622       619.0  2.656652     32.73   

       Longitude  
72       -122.29  
2602     -123.52  
19784    -122.89  
3405     -118.36  
12492    -121.48  
...          ...  
18448    -121.81  
7985     -118.16  
18687    -121.79  
19776    -122.23  
14148    -117.08  

[16512 rows x 8 columns]

In [14]:
from sklearn.linear_model import Ridge
model=Ridge()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.6176737722553938

# for classification 


In [15]:
from sklearn.ensemble import RandomForestClassifier
heart=pd.read_csv("heart-disease.csv")
heart
X=heart.drop("target",axis=1)
y=heart["target"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)


In [16]:
import numpy as np
np.random.seed(43)
model=RandomForestClassifier(n_estimators=100)
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.819672131147541

# Making predictions
# 2ways to make predictions
1.'predict()'

2.predict_proba()

In [17]:
model.predict(X_test) #predicted on X_test data

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [18]:
model.score(X_test,y_test)

0.819672131147541

In [19]:
np.array(y_test) #truth  values of dataset 

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1], dtype=int64)

In [20]:
y_preds=model.predict(X_test)  #comparing the truth labels and describing the mean of it
np.mean(y_test==y_preds)

0.819672131147541

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_preds)

0.819672131147541

# predict_proba()

In [22]:
model.predict_proba(X_test[:5])

array([[0.02, 0.98],
       [0.21, 0.79],
       [0.89, 0.11],
       [0.32, 0.68],
       [0.98, 0.02]])

In [23]:
model.predict(X_test[:5])

array([1, 1, 0, 1, 0], dtype=int64)

# For regression

In [24]:
import pandas as pd
marks=pd.read_csv("Student_Marks.csv")
marks


number_courses  time_study   Marks
0                3       4.508  19.202
1                4       0.096   7.734
2                4       3.133  13.811
3                6       7.909  53.018
4                8       7.811  55.299
..             ...         ...     ...
95               6       3.561  19.128
96               3       0.301   5.609
97               4       7.163  41.444
98               7       0.309  12.027
99               3       6.335  32.357

[100 rows x 3 columns]

In [25]:

marks
marks=marks.rename(columns={'Marks':'target'})
marks


number_courses  time_study  target
0                3       4.508  19.202
1                4       0.096   7.734
2                4       3.133  13.811
3                6       7.909  53.018
4                8       7.811  55.299
..             ...         ...     ...
95               6       3.561  19.128
96               3       0.301   5.609
97               4       7.163  41.444
98               7       0.309  12.027
99               3       6.335  32.357

[100 rows x 3 columns]

# score() & from metrics function 

In [26]:
import numpy as np
X=marks.drop("target",axis=1)
y=marks["target"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

#choosing the model 
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9943969056000739

In [27]:
y_preds=model.predict(X_test)

In [28]:
y_preds

array([27.26354, 23.80603, 40.20555, 52.50772,  7.81973,  6.34118,
       23.29315, 17.19237, 31.71908,  7.87875, 52.85448, 42.79907,
       20.43433,  6.34118, 51.81658,  6.18874, 11.29337, 45.24288,
       23.15725, 16.07443])

In [29]:
np.array(y_test)

array([27.569, 24.451, 40.602, 51.142,  8.837,  6.217, 24.394, 17.264,
       29.889,  8.92 , 54.321, 46.453, 19.202,  6.349, 51.583,  6.185,
       10.522, 44.099, 24.318, 15.725])

In [30]:
y_test.head()

66    27.569
94    24.451
50    40.602
39    51.142
29     8.837
Name: target, dtype: float64

# Evaluating the ML model 

#evaluating the model with score() method'

In [31]:
from sklearn.ensemble import RandomForestClassifier
heart=pd.read_csv("heart-disease.csv")
heart
X=heart.drop("target",axis=1)
y=heart["target"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
import numpy as np
np.random.seed(43)
model=RandomForestClassifier(n_estimators=500)
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=500)

the highest value for the classification is 1.0 and the lowesT is 0.0

In [32]:
model.score(X_train,y_train)

1.0

In [33]:
model.score(X_test,y_test)

0.8032786885245902

# crossvalidation 
normal train test split trains on 80% of data and evaluates on 20% of data
where as cross validation trains on 5differents sets of train data and evaluates on 5 diff sets of test data..(5-fold crossvalidation)

In [34]:
from sklearn.ensemble import RandomForestClassifier
heart=pd.read_csv("heart-disease.csv")
heart
X=heart.drop("target",axis=1)
y=heart["target"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
import numpy as np
#np.random.seed(43)
model=RandomForestClassifier(n_estimators=500)
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=500)

In [35]:
single_score=model.score(X_test,y_test)
single_score

0.8688524590163934

In [36]:
cross_val_score(model,X,y,cv=10)

array([0.90322581, 0.83870968, 0.83870968, 0.9       , 0.9       ,
       0.83333333, 0.66666667, 0.83333333, 0.73333333, 0.8       ])

In [37]:
from sklearn.model_selection import cross_val_score
val_score=np.mean(cross_val_score(model,X,y,cv=5))
val_score

0.8281420765027322

# classification model evaluation metrics
#1. Accracy
2.Area of ROC curve
3.confision matrix
4.classification report
# Accuracy

In [71]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score 

In [75]:
X=heart.drop("target",axis=1)
y=heart["target"]
model=RandomForestClassifier(n_estimators=100)
mean=cross_val_score(model,X,y,cv=5)

In [76]:
print("the cross validation score of heart disease is:",np.mean(mean)*100)


the cross validation score of heart disease is: 81.83060109289617


# Area of ROC curve
1.Area under curve 

2.reciever operating charactersitic curve

roc curve is a comparision between tpr (true positive rate) & fpr (false positive rate)

tpr= model predicts  1 when the truth is 1

fpr= model predicts 1 when the truth is 0 

true negative = model predicts 0 when the truth  is 0

false negative = model predicts 0 when the truth is 1

